### ISSUE TITLE
Individual Column alignment

### ISSUE THREAD

**Issue by shopno111** [joaocarmo/react-smart-data-table#62]
### Expected Behavior

Can we use specific alignment ?, if yes, then how we can do that. 
Suppose I want to do right align in right with header and data .

**Comment by joaocarmo** [comment]
Hi @shopno111, you can use CSS to achieve what you want. Just add this snippet somewhere where your table is being rendered:

```css
/* Targets the head `th` and the body `td` */
.rsdt th, .rsdt td {
  /* You you only need the !important rule if you're overriding some other CSS */
  text-align: right !important;
}
```

**Comment by shopno111** [comment]
as your way it will be all column, I want to do specific column only.

Example : 
I have following columns 
Name, Phone, Email, Date , Amount

Here Name, Phone, Email, Date will be Left Alignment & Amount will be Right Column

**Comment by shopno111** [comment]
In your Headers, if we can do following way, it will be fetter 

 amount: {
            text: "Amount",
            sortable: true,
            filterable: true,
            headerClass: "rightAlign",
            bodyClass: "rightAlign",
            transform: (value, idx, row) => (
                "$ "+value
            )
        }

**Comment by joaocarmo** [comment]
If you know the position of the columns, you can also target that using CSS and the [nth-of-type](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-of-type) selector. For example:

```css
/* Align the 3rd column's content to the right */
.rsdt th:nth-of-type(3), .rsdt td:nth-of-type(3) {
  text-align: right !important;
}
```

Though I understand the limitation. I'm considering adding a [name](https://www.w3schools.com/tags/att_name.asp) attribute to the column (header and body rows) which you can use to easily target using CSS:

```css
/* Align the `amount` column's content to the right */
.rsdt th[name='amount'], .rsdt td[name='amount'] {
  text-align: right !important;
}
```
